version: "3.7"
services:
  db:
    image: mysql:8.0.21
    container_name: underflow_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: stackunderflow
      MYSQL_USER: underflower
      MYSQL_PASSWORD: securepassword
    ports:
      - "3308:3306"
    volumes:
      - ./init/database/:/docker-entrypoint-initdb.d/
      - stackunderflow_db:/var/lib/mysql

  web:
    image: ghcr.io/underflowers/stackunderflow:latest
    container_name: stackunderflow
    volumes:
      - ./src/main/liberty/config/server.env:/config/server.env
    depends_on:
      - db
    network_mode: "host"

volumes:
  stackunderflow_db:
